services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "0.0.0.0:25565:25565"
      - "0.0.0.0:19132:19132/udp"
    env_file:
      - .env
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "LATEST"
      MEMORY: "8G"
      OPS: "momoka_sada"
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - ./minecraft_server:/data
    restart: unless-stopped

  app:
    build: ./kenkoku-manage-service
    volumes:
      - ./kenkoku-manage-service:/workdir
    ports:
      - 8000:8000
  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/initdb:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_USER: ${MYSQL_USER:-minecraft_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-minecraft_password}
    ports:
      - "3306:3306"
